=== 1Nonamed/bryans_cafe/public/branches.dtd
<!ELEMENT branches (branch+)>
<!ELEMENT branch (address, phoneNumber, schedule, variant?)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phoneNumber (#PCDATA)>
<!ELEMENT schedule (#PCDATA | weekdays | weekends)*>
<!ELEMENT weekdays (#PCDATA)>
<!ELEMENT weekends (#PCDATA)>
<!ELEMENT variant (#PCDATA)>

=== 1Nonamed/bryans_cafe/public/branches.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE branches SYSTEM "branches.dtd">
<branches>
    <branch>
        <address>76 Devonshire St Surry Hills, NSW</address>
        <phoneNumber>02 9211 1234</phoneNumber>
        <schedule>
            <weekdays>Mon - Fri: 6:00 - 14:30</weekdays>
            <weekends>Sat - Sun: 7:00 - 15:00</weekends>
        </schedule>
    </branch>
    <branch>
        <address>451 Pitt St, Haymarket Sydney, NSW</address>
        <phoneNumber>02 9262 5678</phoneNumber>
        <schedule>
            <weekdays>Mon - Fri: 6:00 - 16:00</weekdays>
            <weekends>Sat - Sun: 7:00 - 15:00</weekends>
        </schedule>
    </branch>
    <branch>
        <address>31 Alfred St, Circular Quay, NSW</address>
        <phoneNumber>02 8971 9101</phoneNumber>
        <schedule>
            <weekdays>Mon - Fri: 6:00 - 16:00</weekdays>
            <weekends>Sat - Sun: 7:00 - 15:00</weekends>
        </schedule>
    </branch>
</branches>
